# docker-compose.yml
version: '3.8'

services:
  api:
    build: ./vote-api
    ports:
      - "8080:8080"
    environment:
      - PG_URL=postgres://vote_user:password123@db:5432/vote_db?sslmode=disable
      - JSON_LOG=true
    depends_on:
      db:
        condition: service_healthy

  web-client: 
    build: 
      context: ./web-client
    ports:
      - "3000:3000"
    environment:
      - VOTE_API_BASE_URL=http://api:8080
    depends_on:
      - api
  docs:
        build:
          context: ./docs
        ports:
          - "4000:80"
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=vote_user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=vote_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vote_user -d vote_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: