name: Go CI

on:
  push:
    branches:
      - main
      - develop
      - feature/pipelineTest
  pull_request:
    branches:
      - main
      - develop
      - feature/pipelineTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        working-directory: vote-api
        run: go mod tidy

      - name: Run tests
        working-directory: vote-api
        run: go test ./... -v