name: Go CI

on:
  push:
    branches:
      - main
      - develop
      - feature/pipelineTest
  pull_request:
    branches:
      - main
      - develop
      - feature/pipelineTest

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Postgres is ready" && exit 0
            echo "Waiting for Postgres..."
            sleep 3
          done
          echo "Postgres failed to start" && exit 1

      - name: Set environment variables
        env:
          PG_URL: ${{ secrets.PG_URL }}
        run: echo "PG_URL=${{ secrets.PG_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: vote-api
        run: go mod tidy

      - name: Run tests
        working-directory: vote-api
        run: go test ./... -v